// <auto-generated />
using KraftwerkAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KraftwerkAPI.Migrations
{
    [DbContext(typeof(RobotContext))]
    [Migration("20200306170808_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("KraftwerkAPI.Models.RobotModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Head")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftArm")
                        .HasColumnType("TEXT");

                    b.Property<string>("RightArm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Robot");
                });
#pragma warning restore 612, 618
        }
    }
}
